# Search Configuration Profiles for PS Ticket Process Bot
# Only keeping new ticket search with 1-minute frequency

# New ticket search for recently created issues
new_tickets:
  name: "New Ticket Search"
  description: "Search for newly created tickets"
  enabled: true
  schedule: "*/1 * * * *"  # Every 1 minute
  config:
    projects: ["PS"]
    issue_types: ["Problem", "Bug", "Support Request"]
    statuses: ["Open"]
    time_range_hours: 2
    batch_size: 30
    exclude_processed_within_hours: 1
    # Use created date instead of updated date
    time_field: "created"
  priority: "high"
