# Production Environment Configuration
environment: production

# Application Settings
app:
  name: "PS Ticket Bot"
  version: "0.1.0"
  debug: false
  host: "0.0.0.0"
  port: 8000
  reload: false

# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - console
    - file
    - syslog
  file_path: "logs/production.log"
  max_file_size: "100MB"
  backup_count: 30
  syslog_address: "/dev/log"

# Database Configuration
database:
  url: "${DATABASE_URL}"
  echo: false
  pool_size: 20
  max_overflow: 40
  pool_pre_ping: true
  pool_recycle: 3600

# Redis Configuration
redis:
  url: "${REDIS_URL}"
  db: 0
  decode_responses: true
  socket_timeout: 10
  socket_connect_timeout: 10
  retry_on_timeout: true
  max_connections: 50

# JIRA Configuration
jira:
  base_url: "${JIRA_BASE_URL}"
  username: "${JIRA_USERNAME}"
  api_token: "${JIRA_API_TOKEN}"
  timeout: 30
  max_retries: 5
  retry_delay: 2
  verify_ssl: true

# Gemini API Configuration
gemini:
  api_key: "${GEMINI_API_KEY}"
  model: "${GEMINI_MODEL:-gemini-pro}"
  timeout: 30
  max_retries: 5
  retry_delay: 2

# Queue Configuration
queue:
  broker_url: "${REDIS_URL}"
  result_backend: "${REDIS_URL}"
  task_serializer: "json"
  accept_content: ["json"]
  result_serializer: "json"
  timezone: "UTC"
  enable_utc: true
  worker_concurrency: 8
  worker_prefetch_multiplier: 1
  task_acks_late: true
  worker_disable_rate_limits: false

# Webhook Configuration
webhook:
  secret: "${JIRA_WEBHOOK_SECRET}"
  verify_signature: true
  timeout: 30

# Security Configuration
security:
  secret_key: "${SECRET_KEY}"
  algorithm: "HS256"
  access_token_expire_minutes: 30

# Feature Flags
features:
  enable_webhooks: true
  enable_polling: false
  enable_ai_comments: true
  enable_status_transitions: true
  enable_notifications: true
  enable_metrics: true
  enable_health_checks: true

# Monitoring Configuration
monitoring:
  enable_prometheus: true
  prometheus_port: 8001
  health_check_interval: 30
  metrics_prefix: "ps_ticket_bot"
  alert_thresholds:
    error_rate: 0.05  # 5%
    response_time_p95: 5.0  # 5 seconds
    queue_depth: 1000

# Production-specific settings
production:
  high_availability: true
  auto_scaling: true
  backup_enabled: true
  audit_logging: true
  notification_channels:
    - "#production-alerts"
    - "alerts@company.com"
  data_retention_days: 90
  
# Rate Limiting
rate_limiting:
  enabled: true
  requests_per_minute: 100
  burst_limit: 200
  
# Circuit Breaker
circuit_breaker:
  enabled: true
  failure_threshold: 5
  recovery_timeout: 60
  expected_exception: "requests.exceptions.RequestException"
